name: Notify Slack
on:
  pull_request:
    types: [closed]
    branches: 
      - beta
      - master
jobs:
  slack-notification:
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repository
        uses: actions/checkout@v2
      - name: slack-notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: digital_innovation_team
          SLACK_USERNAME: "GitHub Notification Bot"
          #SLACK_ICON: "https://imageurl.com"
          SLACK_ICON_EMOJI: ":mega:"
          #SLACK_COLOR: "#EEEEEE"
          SLACK_MESSAGE: ${{ github.event.pull_request.body }}
          SLACK_TITLE: "New Code Deployed to BETA"
          SLACK_FOOTER: "Powered By MOF GitHub Actions Library"
          MSG_MINIMAL: ref, event, commit
