name: Notify Slack
on:
  pull_request:
    types: [closed]
    branches: 
      - beta
jobs:
  slack-notification:
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repository
        uses: actions/checkout@v2
      - name: get-commit-message
        run: |
          echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
      - name: show-commit-message
        run: echo $commitmsg
      - name: slack-notification
        uses: rtCamp/action-slack-notify@v2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: digital_innovation_team
          SLACK_USERNAME: "GitHub Notification Bot"
          #SLACK_MSG_AUTHOR: $GITHUB_ACTOR
          #SLACK_ICON: "https://imageurl.com"
          SLACK_ICON_EMOJI: ":bell:"
          #SLACK_COLOR: "#EEEEEE"
          SLACK_MESSAGE: $commitmsg
          SLACK_TITLE: "New Code Deployed to BETA"
          SLACK_FOOTER: "Powered By MOF GitHub Actions Library"
