name: Merge Master into Beta
on:
  pull_request:
    types: [closed]
    branches: 
      - master
jobs:
  master-to-beta:
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: configure-github-user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: checkout-beta
        run: |
          git checkout beta
      - name: merge-master
        run: |
          git merge master
