name: Auto-Generate PR into Master
on:
  push:
    branches:
      - beta
jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v2
      - name: set-from-branch-name
        run: |
          echo Push Ref ${{ github.push.ref }}
          echo Event Push Ref ${{ github.event.push.ref }}
          echo Master Branch ${{ github.event.master_branch }}
          echo Event Ref ${{ github.event.ref }}
          echo Ref ${{ github.ref }}
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "master"
          PULL_REQUEST_FROM_BRANCH: "test"
