name: Auto-Generate PR into Master
on:
  push:
    branches:
      - beta
jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v2
      - name: set-from-branch-name
        run: |
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.event.ref }}
          echo ${{ github.ref }}
          export "PULL_REQUEST_FROM_BRANCH=${{ github.payload.pull_request.head.ref }}" >> $GITHUB_ENV
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "master"
